spring:
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      allow.auto.create.topics: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: notification-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9098/realms/erp-bh"
          #jwk-set-uri: "http://localhost:9098/realms/erp-bh/protocol/openid-connect/certs"
  rabbitmq:
    host: localhost
    port: 5672
    username: erp
    password: erp
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true

  datasource:
    username: admin
    password: ""
    url: jdbc:h2:file:./Database/Data/budget
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create

server:
  servlet:
    context-path: /api/v1
  port: 8020
application:
  config:
    project-url: http://localhost:8024/api/v1/projets