spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9098/realms/erp-bh"
          jwks_uri: "http://localhost:9098/realms/erp-bh/protocol/openid-connect/certs"
  rabbitmq:
    host: localhost
    port: 5672
    username: erp
    password: erp
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true

  datasource:
    username: admin
    password: ""
    url: jdbc:h2:file:./Database/Data/entreprise
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8021
