spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true

  datasource:
    username: admin
    password: ""
    url: jdbc:h2:file:./Database/Data/finance
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8023
