spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: erp
    password: erp
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true

  datasource:
    username: admin
    password: ""
    url: jdbc:h2:file:./Database/Data/projet
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create

server:
  servlet:
    context-path: /api/v1
  port: 8024
